name: pyllments
channels:
  - conda-forge
dependencies:
  - numpy
  - python-dotenv
  - bokeh
  - panel
  - langchain
  - langchain-openai
  - sentence-transformers
  - openai
  - jsonlines
  - opencv
  - pdfminer.six
  - pikepdf
  - pip==24.0
  - pip:
    - nbconvert
    - tiktoken
    - chromadb
    - unstructured
    - pillow-heif
    - pytesseract
    - langchain-community
    - langchain-chroma
    - langchain-anthropic
    - ruamel.yaml
